import type { Metadata } from "next";
import "@/assets/styles/globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "NextTS Challenges",
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg",
  },
};

interface Props {
  children: React.ReactNode;
}

const MainLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <body>
        <div id="overlay"></div>
        <Header />
        <main className="h-full w-full min-h-screen pt-20 bg-slate-100">
          {children}
        </main>
      </body>
    </html>
  );
};

export default MainLayout;
