import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "NextTS Challenges",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

const MainLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default MainLayout;
